# AWSTemplateFormatVersion: '2010-09-09'
# Resources:
  
#   IAMGroupAdmins:
#     Type: AWS::IAM::Group
#     Properties: 
#       GroupName: ETNetwork-Admins
#       Path: /
#       ManagedPolicyArns:
#         - arn:aws:iam::aws:policy/AmazonRDSFullAccess
#         - arn:aws:iam::aws:policy/IAMSelfManageServiceSpecificCredentials
#         - arn:aws:iam::aws:policy/IAMReadOnlyAccess
#         - arn:aws:iam::aws:policy/AmazonRoute53FullAccess
#         - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
#         - arn:aws:iam::aws:policy/AmazonElastiCacheFullAccess
#         - arn:aws:iam::aws:policy/AmazonSQSFullAccess
#         - arn:aws:iam::aws:policy/AmazonS3FullAccess
#         - arn:aws:iam::aws:policy/AmazonESFullAccess
#         - arn:aws:iam::aws:policy/CloudWatchFullAccess

#   GroupAddition:
#    Type: AWS::IAM::UserToGroupAddition
#    Properties: 
#       GroupName: !Ref IAMGroupAdmins
#       Users: 
#         - atul
#         - Ashwani
#         - user_2
#         - user_1

#   IAMPolicyAdminsDefault:
#     Type: 'AWS::IAM::Policy'
#     Properties:
#       PolicyName: ETNetwork-IamUsersAdminsPolicy
#       Groups:
#         - !Ref IAMGroupAdmins          
#       PolicyDocument: 
#         Version: 2012-10-17
#         Statement:
#           - Sid: "DenySomeActions"
#             Effect: Deny
#             Action:
#               - "rds:DeleteDBCluster"
#               - "rds:DeleteDBClusterEndpoint"
#               - "rds:DeleteDBClusterParameterGroup"
#               # - "rds:DescribeDBInstances"
#               - "rds:DeleteDBInstance"
#               # - "DescribeDBSnapshots"
#               - "rds:DeleteDBInstanceAutomatedBackup"
#               - "rds:DeleteDBParameterGroup"
#               - "rds:DeleteDBProxy"
#               - "rds:DeleteDBSecurityGroup"
#               - "rds:DeleteDBSubnetGroup"
#               - "rds:DeleteEventSubscription"
#               - "rds:DeleteGlobalCluster"
#               - "rds:DeleteOptionGroup" 
#               - "rds:DeleteDBSnapshot"
#               - "rds:DeregisterDBProxyTargets"
#             Resource: '*'

  IAMPolicyAdminsDefault1:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: IAM_policy
      PolicyName: ETNetwork-IamUsersAdminsPolicy
      Groups:
        - !Ref IAMGroupAdmins          
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Sid: "AllowSomeActions"
            Effect: Allow
            Action:
                - "rds:DeleteDBCluster"
              # - "rds:DeleteDBClusterEndpoint"
              #  - "rds:DeleteDBClusterParameterGroup"
              - "rds:DeleteDBClusterSnapshot"
              - "rds:DescribeDBInstances"
              - "rds:DescribeDBSnapshots"
              # - "rds:DeleteDBInstance"
              # - "rds:DeleteDBInstanceAutomatedBackup"
              # - "rds:DeleteDBParameterGroup"
              # - "rds:DeleteDBProxy"
              # - "rds:DeleteDBSecurityGroup"
              # - "rds:DeleteDBSubnetGroup"
              # - "rds:DeleteEventSubscription"
              # - "rds:DeleteGlobalCluster"
              # - "rds:DeleteOptionGroup" 
                - "rds:DeleteDBSnapshot"
              #- "rds:DeregisterDBProxyTargets"
            Resource:
                    - arn:aws:rds:*:userid:user/user_1        